FROM ubuntu:latest

RUN apt update && apt install -y nodejs npm

WORKDIR /app

COPY ./src ./src

COPY ./package.json .

RUN npm install -g nodemon

RUN npm install

EXPOSE 3000

CMD ["npm", "run", "dev"]
