name: Dockerize Code with GitHub Actions

on:
  push:
    branches: [main]  

jobs:
   BuildContainer:
    name: Docker build
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build --platform linux --tag andry510/example:latest -f src/dockerFile .
        
      - name: Push Docker image to Docker Hub
        run: docker push andry510/example:latest

      - name: Run Docker image
        run: docker run -d -p 3000:80 andry510/example:latest